FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY . .
RUN mvn -q -pl zero-trust-demo -am -DskipTests package dependency:copy-dependencies -DincludeScope=runtime -Dmdep.outputDirectory=/workspace/zero-trust-demo/target/dependency

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /workspace/zero-trust-demo/target/classes /app/classes
COPY --from=build /workspace/zero-trust-demo/target/dependency /app/lib
ARG MAIN_CLASS
ENV MAIN_CLASS=${MAIN_CLASS}
ENV JAVA_OPTS=""
ENV SPRING_ARGS=""
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -cp '/app/classes:/app/lib/*' $MAIN_CLASS $SPRING_ARGS"]
